#pragma once

#define DISPLAY_COLOR_SCREEN_BG        0x080808
#define DISPLAY_COLOR_SCREEN_PANEL     0x121212
#define DISPLAY_COLOR_SCREEN_DIVIDER   0x1f1f1f

#define DISPLAY_COLOR_MOD_ACTIVE       0xf0d891
#define DISPLAY_COLOR_MOD_INACTIVE     0x4b463a
#define DISPLAY_COLOR_MOD_SEPARATOR    0x323232
#define DISPLAY_COLOR_MOD_CAPS_WORD    0xffbf00

#define DISPLAY_COLOR_WPM_BAR_ACTIVE   0xd36a3c
#define DISPLAY_COLOR_WPM_BAR_INACTIVE 0x1f1f1f
#define DISPLAY_COLOR_WPM_TEXT         0xe78a5a
#define DISPLAY_COLOR_WPM_TREND_UP     0xb4d87c
#define DISPLAY_COLOR_WPM_TREND_DOWN   0xd97a7a
#define DISPLAY_COLOR_WPM_TREND_STEADY 0x898989

#define DISPLAY_COLOR_LAYER_TEXT       0xf4f1ea
#define DISPLAY_COLOR_LAYER_DOT_ACTIVE   0xe2ba74
#define DISPLAY_COLOR_LAYER_DOT_INACTIVE 0x464646

#define DISPLAY_COLOR_BATTERY_FILL     0x6e9d7d
#define DISPLAY_COLOR_BATTERY_RING     0x2d4839
#define DISPLAY_COLOR_BATTERY_BG       0x505050
#define DISPLAY_COLOR_BATTERY_LABEL    0xffffff

#define DISPLAY_COLOR_BATTERY_DISCONNECTED_FILL  0x383c42
#define DISPLAY_COLOR_BATTERY_DISCONNECTED_RING  0x282c30
#define DISPLAY_COLOR_BATTERY_DISCONNECTED_LABEL 0x000000

#define DISPLAY_COLOR_BATTERY_LOW_FILL  0xC08040
#define DISPLAY_COLOR_BATTERY_LOW_RING  0x584028

#define DISPLAY_COLOR_USB_ACTIVE_BG        0xe1cf9f
#define DISPLAY_COLOR_USB_INACTIVE_BG      0x524a3a
#define DISPLAY_COLOR_BLE_ACTIVE_BG        0x73a2ac
#define DISPLAY_COLOR_BLE_INACTIVE_BG      0x304046
#define DISPLAY_COLOR_OUTPUT_ACTIVE_TEXT   0x000000
#define DISPLAY_COLOR_OUTPUT_INACTIVE_TEXT 0x8f8f8f

#define DISPLAY_COLOR_SLOT_ACTIVE_BG   0xb18a5f
#define DISPLAY_COLOR_SLOT_INACTIVE_BG 0x2f2f2f
#define DISPLAY_COLOR_SLOT_TEXT        0xffffff
